### ISSUE TITLE
multiplying

### ISSUE THREAD

**Issue by mrfltvs** [JSMongere/Test2#1]
cpp
#include <iostream>

int multiply(int num1, int num2) {
    return num1 * num2;
}

int main() {
    int num1, num2;
    
    std::cout << "Enter two numbers: ";
    std::cin >> num1 >> num2;
    
    int result = multiply(num1, num2);
    
    std::cout << "Result: " << result << std::endl;
    
    return 0;
}

**Comment by JSMongere** [comment]
Thanks

**Comment by mrfltvs** [comment]
welcome
